server:
  port: 9991

tencent-cos:
  baseUrl: https://adachi-1308253768.cos.ap-guangzhou.myqcloud.com
  accessKey: AKIDtjjbIrIcnodGj3iEj7KLg7Qdrvz1seHk
  secretKey: PhomZBammcGnOp6A0qHajv0xiEi3FF6t
  regionName: ap-guangzhou
  bucketName: adachi-1308253768
  folderPrefix: /files